import fs from 'fs';

const currentCategories = [
  "Acessórios",
  "Bobina de ignição",
  "Carburadores",
  "Carcaça",
  "Carenagem",
  "Carenagem/Plásticos",
  "CDI",
  "Chicotes",
  "Cilindro",
  "Corrente de comando",
  "Cubo",
  "Disco de freio",
  "Eixo de partida",
  "Eletroventilador",
  "Embreagem",
  "Engrenagem de comando",
  "Engrenagem de partida",
  "Escapamentos",
  "Estator",
  "Farol",
  "Filtro centrífugo",
  "Filtro de Ar",
  "Filtro de óleo",
  "Flange e Coroa",
  "Freios",
  "Frete",
  "Ignição",
  "KIT",
  "Kit de Partida",
  "Lanterna",
  "Magneto",
  "Manicoto",
  "Mesas",
  "Módulo ABS",
  "Módulos de Injeção (Central)",
  "Moto",
  "Motor",
  "Motor de partida",
  "Painéis",
  "Peças de Arrefecimento",
  "Peças Elétricas",
  "Pedal de freio",
  "Pedal de marcha",
  "Pedaleiras",
  "Pinça de freio",
  "Placa de partida",
  "Pneu",
  "Quadro",
  "Rabeta",
  "Radiador",
  "Relé de partida",
  "Retificador",
  "Rodas",
  "Roupa",
  "Sensor de velocidade",
  "Setas",
  "Sistema de injeção",
  "Sonda Lambda",
  "Suporte de Pedaleiras",
  "Tampa da embreagem",
  "Tampa da Lanterna",
  "Tampa do cabeçote",
  "Tampa do cubo",
  "Tampa do Estator",
  "Tampa do Magneto",
  "Tanques",
  "TBI",
  "Transmissão",
  "Virabrequins"
];

const notionCategories = [
  "Acelerador",
  "Acessórios",
  "Amortecedor",
  "Aranha",
  "Assentos/Bancos",
  "Balança",
  "Bengala",
  "Bloco",
  "Bloco do farol (Frente)",
  "Bobina de ignição",
  "Bomba de Combustível",
  "CDI",
  "Cabeçote",
  "Caixa da bateria",
  "Caixa de marcha",
  "Caixa do filtro de ar",
  "Carburadores",
  "Carcaça",
  "Carenagem",
  "Carenagem/Plásticos",
  "Catalizador",
  "Chicotes",
  "Cilindro",
  "Corrente de comando",
  "Cubo",
  "Disco de freio",
  "Eixo de partida",
  "Eletroventilador",
  "Embreagem",
  "Engrenagem de comando",
  "Engrenagem de partida",
  "Escapamento",
  "Escapamentos",
  "Estator",
  "Farol",
  "Filtro centrifugo",
  "Filtro de Ar",
  "Filtro de óleo",
  "Flange e Coroa",
  "Freios",
  "Frete",
  "Ignição",
  "KIT",
  "Kit de Partida",
  "Lanterna",
  "Magneto",
  "Mangueira de combustível ",
  "Manicoto",
  "Mesas",
  "Moto",
  "Motor",
  "Motor de partida",
  "Motores",
  "Módulo ABS",
  "Módulos de Injeção (Central)",
  "Painéis",
  "Pedal de freio",
  "Pedal de marcha",
  "Pedaleiras",
  "Peças Elétricas",
  "Peças de Arrefecimento",
  "Pinça de freio",
  "Placa de partida",
  "Pneu",
  "Quadro",
  "Rabeta",
  "Radiador",
  "Relé de partida",
  "Retificador",
  "Rodas",
  "Roupa",
  "Sensor de velocidade",
  "Setas",
  "Sistema de injeção",
  "Sonda Lambda",
  "Suporte de Pedaleiras",
  "TBI",
  "Tampa da Lanterna",
  "Tampa da embreagem",
  "Tampa do Estator",
  "Tampa do Magneto",
  "Tampa do cabeçote",
  "Tampa do cubo",
  "Tampa do pião",
  "Tanques",
  "Transmissão",
  "Virabrequins"
];

const currentMotos = [
  "50CC",
  "ADV",
  "BIZ 125",
  "BROS 150",
  "BROS 160",
  "CB 300R",
  "CB 500F",
  "CB TWISTER 250",
  "CBX TWISTER 250",
  "CG 125",
  "CG 150",
  "CG 160",
  "DREAM 100",
  "FACTOR",
  "FAZER 250",
  "FALCON 400",
  "MT-03",
  "MT-09",
  "POP 100",
  "POP 110i",
  "START",
  "STRADA 200",
  "TWISTER 250",
  "XMAX",
  "XRE 190",
  "XRE 300",
  "XTZ 125E",
  "XY 50 QJET",
  "YBR"
];

const notionMotos = [
  "Bicicleta Motorizada 80cc",
  "CB 500F",
  "CB TWISTER 250",
  "CBX TWISTER 250",
  "CG 125",
  "CG 125 CARGO",
  "CG 125 KS",
  "CG 150",
  "FALCON 400",
  "FAZER 250",
  "POP 100",
  "SAZAKI 50 JET",
  "SUNDOW HUNTER 100",
  "SUZUKI INTRUDER",
  "TRAXX JL50Q (14)",
  "XTZ 125XE"
];

const allCategories = Array.from(new Set([...currentCategories, ...notionCategories.map(c => c.trim())]));
const allMotos = Array.from(new Set([...currentMotos, ...notionMotos.map(m => m.trim())]));

// Remove duplicates like "Escapamento" and "Escapamentos"
const filteredCategories = allCategories.filter(c => {
  if (c === "Escapamento") return false;
  if (c === "Filtro centrifugo") return false;
  return true;
});

filteredCategories.sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));
allMotos.sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));

console.log("export const CATEGORIAS_OFICIAIS = [");
filteredCategories.forEach(c => console.log(`  "${c}",`));
console.log("].sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));\n");

console.log("export const MOTOS_OFICIAIS = [");
allMotos.forEach(m => console.log(`  "${m}",`));
console.log("].sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));\n");
