export const CATEGORIAS_OFICIAIS = [
  "Acessórios",
  "Bobina de ignição",
  "Carburadores",
  "Carcaça",
  "Carenagem",
  "Carenagem/Plásticos",
  "CDI",
  "Chicotes",
  "Cilindro",
  "Corrente de comando",
  "Cubo",
  "Disco de freio",
  "Eixo de partida",
  "Eletroventilador",
  "Embreagem",
  "Engrenagem de comando",
  "Engrenagem de partida",
  "Escapamentos",
  "Estator",
  "Farol",
  "Filtro centrífugo",
  "Filtro de Ar",
  "Filtro de óleo",
  "Flange e Coroa",
  "Freios",
  "Frete",
  "Ignição",
  "KIT",
  "Kit de Partida",
  "Lanterna",
  "Magneto",
  "Manicoto",
  "Mesas",
  "Módulo ABS",
  "Módulos de Injeção (Central)",
  "Moto",
  "Motor",
  "Motor de partida",
  "Painéis",
  "Peças de Arrefecimento",
  "Peças Elétricas",
  "Pedal de freio",
  "Pedal de marcha",
  "Pedaleiras",
  "Pinça de freio",
  "Placa de partida",
  "Pneu",
  "Quadro",
  "Rabeta",
  "Radiador",
  "Relé de partida",
  "Retificador",
  "Rodas",
  "Roupa",
  "Sensor de velocidade",
  "Setas",
  "Sistema de injeção",
  "Sonda Lambda",
  "Suporte de Pedaleiras",
  "Tampa da embreagem",
  "Tampa da Lanterna",
  "Tampa do cabeçote",
  "Tampa do cubo",
  "Tampa do Estator",
  "Tampa do Magneto",
  "Tanques",
  "TBI",
  "Transmissão",
  "Virabrequins"
].sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));

export const MOTOS_OFICIAIS = [
  "50CC",
  "ADV",
  "BIZ 125",
  "BROS 150",
  "BROS 160",
  "CB 300R",
  "CB 500F",
  "CB TWISTER 250",
  "CBX TWISTER 250",
  "CG 125",
  "CG 150",
  "CG 160",
  "DREAM 100",
  "FACTOR",
  "FAZER 250",
  "FALCON 400",
  "MT-03",
  "MT-09",
  "POP 100",
  "POP 110i",
  "START",
  "STRADA 200",
  "TWISTER 250",
  "XMAX",
  "XRE 190",
  "XRE 300",
  "XTZ 125E",
  "XY 50 QJET",
  "YBR"
].sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));

export const PAGAMENTOS_OFICIAIS = [
  "CRÉDITO",
  "DÉBITO",
  "DINHEIRO",
  "MARCELO",
  "PENDÊNCIA",
  "PIX"
].sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));
