export const CATEGORIAS_OFICIAIS = [
  "Acelerador",
  "Acessórios",
  "Amortecedor",
  "Aranha",
  "Assentos/Bancos",
  "Balança",
  "Bengala",
  "Bloco",
  "Bloco do farol (Frente)",
  "Bobina de ignição",
  "Bomba de Combustível",
  "Cabeçote",
  "Caixa da bateria",
  "Caixa de marcha",
  "Caixa do filtro de ar",
  "Carburadores",
  "Carcaça",
  "Carenagem",
  "Carenagem/Plásticos",
  "Catalizador",
  "CDI",
  "Chicotes",
  "Cilindro",
  "Corrente de comando",
  "Cubo",
  "Disco de freio",
  "Eixo de partida",
  "Eletroventilador",
  "Embreagem",
  "Engrenagem de comando",
  "Engrenagem de partida",
  "Escapamentos",
  "Estator",
  "Farol",
  "Filtro centrífugo",
  "Filtro de Ar",
  "Filtro de óleo",
  "Flange e Coroa",
  "Freios",
  "Frete",
  "Ignição",
  "KIT",
  "Kit de Partida",
  "Lanterna",
  "Magneto",
  "Mangueira de combustível",
  "Manicoto",
  "Mesas",
  "Módulo ABS",
  "Módulos de Injeção (Central)",
  "Moto",
  "Motor",
  "Motor de partida",
  "Motores",
  "Painéis",
  "Peças de Arrefecimento",
  "Peças Elétricas",
  "Pedal de freio",
  "Pedal de marcha",
  "Pedaleiras",
  "Pinça de freio",
  "Placa de partida",
  "Pneu",
  "Quadro",
  "Rabeta",
  "Radiador",
  "Relé de partida",
  "Retificador",
  "Rodas",
  "Roupa",
  "Sensor de velocidade",
  "Setas",
  "Sistema de injeção",
  "Sonda Lambda",
  "Suporte de Pedaleiras",
  "Tampa da embreagem",
  "Tampa da Lanterna",
  "Tampa do cabeçote",
  "Tampa do cubo",
  "Tampa do Estator",
  "Tampa do Magneto",
  "Tampa do pião",
  "Tanques",
  "TBI",
  "Transmissão",
  "Virabrequins",
].sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));

export const MOTOS_OFICIAIS = [
  "50CC",
  "ADV",
  "Bicicleta Motorizada 80cc",
  "BIZ 125",
  "BROS 150",
  "BROS 160",
  "CB 300R",
  "CB 500F",
  "CB TWISTER 250",
  "CBX TWISTER 250",
  "CG 125",
  "CG 125 CARGO",
  "CG 125 KS",
  "CG 150",
  "CG 160",
  "DREAM 100",
  "FACTOR",
  "FALCON 400",
  "FAZER 250",
  "MT-03",
  "MT-09",
  "POP 100",
  "POP 110i",
  "SAZAKI 50 JET",
  "START",
  "STRADA 200",
  "SUNDOW HUNTER 100",
  "SUZUKI INTRUDER",
  "TRAXX JL50Q (14)",
  "TWISTER 250",
  "XMAX",
  "XRE 190",
  "XRE 300",
  "XTZ 125E",
  "XTZ 125XE",
  "XY 50 QJET",
  "YBR",
].sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));

export const PAGAMENTOS_OFICIAIS = [
  "CRÉDITO",
  "DÉBITO",
  "DINHEIRO",
  "MARCELO",
  "PENDÊNCIA",
  "PIX"
].sort((a, b) => a.localeCompare(b, 'pt', { sensitivity: 'base' }));
